---
title: "Decentraland"
output: 
  flexdashboard::flex_dashboard:
    theme: spacelab
runtime: shiny
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = FALSE)
# Decentraland pull data using The Graph
library(ghql)
library(jsonlite)
library(tidyverse)
library(lubridate)
library(flexdashboard)
library(shiny)
library(plotly)
library(pins)
# Point to the correct board
board_register(name = "pins_board", 
                url = "https://raw.githubusercontent.com/predictcrypto/pins/master/", 
              board = "datatxt")
# Pull the data
data = pin_get(name = "decentraland_MANA_orders")
# Only keep rows where price USD is present
data = filter(data, is.na(price_USD)==F)
```


Column {.sidebar}
-----------------------------------------------------------------------

x-coordinate range:
```{r}
sliderInput('x_range', '', 
            min=min(as.numeric(data$x), na.rm = T), 
            max=max(as.numeric(data$x), na.rm = T), 
            value = c(min(as.numeric(data$x), na.rm = T), 
                      max(as.numeric(data$x), na.rm = T))) 
```

y-coordinate range:
```{r}
sliderInput('y_range', '', 
            min=min(as.numeric(data$y), na.rm = T), 
            max=max(as.numeric(data$y), na.rm = T), 
            value = c(min(as.numeric(data$y), na.rm = T), 
                      max(as.numeric(data$y), na.rm = T))) 
```

Transaction Date range:
```{r}
dateRangeInput('date_transaction',
               label = '',
               start = as.character(min(as.Date(substr(data$date, 1,10))), na.rm=T),
               end = as.character(max(as.Date(substr(data$date, 1,10))), na.rm=T))
```

Size of area to calculate `area_avg_price` (shown on map)

```{r}
selectInput('area', '', choices=c('20', '50', '100'))
```

<!-- MANA price range: -->
<!-- ```{r} -->
<!-- sliderInput('mana_range', '', min=0, max=1000000, value = c(0,500000), step = 10) -->
<!-- ``` -->

USD price range: 

```{r}
sliderInput('usd_range', '', min=0, max=max(data$price_USD, na.rm = T), value = c(0,50000), step = 10)
```

Column {.tabset}
-----------------------------------------------------------------------

### Map by Price (USD)

```{r}
renderPlotly({
  # Filter data
  data_t = filter(data, x >= input$x_range[[1]], x <= input$x_range[[2]], 
                y >= input$y_range[[1]], y <= input$y_range[[2]],
                price_USD >= input$usd_range[[1]], 
                price_USD <= input$usd_range[[2]],
                date >= input$date_transaction[[1]],
                date <= input$date_transaction[[2]])
  # Only keep latest record per coordinate
  data_t = data_t %>% 
      group_by(x, y) %>% 
      arrange(purchasedAt) %>%  
      slice(n())
  # Show plot
  plot_ly( data_t, x = ~x, y = ~y,
          # Hover text:
          text = ~paste("x: ", x, '<br>y:', y, '<br>Price ($):', price_USD),
          type = 'scatter',
          mode='markers',
          marker=list(
          color = ~price_USD,
          size = 9,
          colorbar=list(title='Price USD'),
          colorscale='Electric') ) %>%
  layout(xaxis = list(
           zerolinecolor = '#ffff',
           zerolinewidth = 2,
           gridcolor = 'ffff',
           showgrid = FALSE),
         yaxis = list(
           zerolinecolor = '#ffff',
           zerolinewidth = 2,
           gridcolor = 'ffff',
           showgrid = FALSE))
})
```


### Map - Area Average Price

```{r}
renderPlot({
  # Filter data
  data_t = filter(data, x >= input$x_range[[1]], x <= input$x_range[[2]], 
                y >= input$y_range[[1]], y <= input$y_range[[2]],
                price_USD >= input$usd_range[[1]], 
                price_USD <= input$usd_range[[2]],
                date >= input$date_transaction[[1]],
                date <= input$date_transaction[[2]])#,
                # transaction_date_created >= input$date_created[[1]],
                # transaction_date_created <= input$date_created[[2]])
  # Show plot - based on size of area chosen
  if (input$area == '20'){
    ggplot(data_t, aes(x, y)) +
    geom_tile(aes(fill = area_avg_price_USD_20, width = 5L, height=5L))  +
    scale_fill_viridis_c(option = "C")
  } else if (input$area == '50'){
      ggplot(data_t, aes(x, y)) +
    geom_tile(aes(fill = area_avg_price_USD_50, width = 5L, height=5L))  +
    scale_fill_viridis_c(option = "C")
  } else{
    ggplot(data_t, aes(x, y)) +
    geom_tile(aes(fill = area_avg_price_USD_100, width = 5L, height=5L))  +
    scale_fill_viridis_c(option = "C")
  }
})
```

